#' Adds PubMed ID to the dataframe of an author generated by `author_as_df`
#'
#' @param author_df a dataframe of an author made by `author_as_df()`
#' @param pmid A character vector with a PubMed ID of a publication made by the author
#'
#' @return the author_df given as a parameter with an extra column with the PubMed ID given in pmid
#' @export
#'
#' @examples
#' pmids <- get_pmids("Benjamin Valderrama")
#' list_of_author_pubs <- lapply(pmids, get_authors_node) |>
#' lapply(function(x){lapply(x, author_as_df) } ) |>
#' lapply(function(x) do.call(rbind, x))
#'
#' coauthors_df <- base::Map(f = add_pmid_to_author_df, list_of_author_pubs, as.list(pmids)) |>
#' do.call(what = "rbind") |>
#' subset(full_name != clean_author_name)
add_pmid_to_author_df <- function(author_df, pmid){

        author_df$PMID <- pmid
        return(author_df)

}
