#' Adds PubMed ID to the dataframe of an author generated by `author_as_df`
#'
#' @param author_df a dataframe of an author made by `author_as_df()`
#' @param pmid A character vector with a PubMed ID of a publication made by the author
#'
#' @return the author_df given as a parameter with an extra column with the PubMed ID given in pmid
#' @export
#'
#' @examples
#' pmids <- get_pmids("Benjamin Valderrama")
#' pmid <- pmids[1]
#'
#' authors <- get_authors_node(pmid)
#' author <- authors[1]
#'
#' author_df <- author_as_df(author)
#'
#' add_pmid_to_author_df(author_df, pmid)
add_pmid_to_author_df <- function(author_df, pmid){

        author_df$PMID <- pmid
        return(author_df)

}
